@startuml 004_ReadingAirInterfaceCapabilitiesFromCache
skinparam responseMessageBelowArrow true

title
RequestForProvidingHistoricalPmDataCausesReadingAirInterfaceCapabilitiesFromCache
end title

participant "LinkVis" as LinkVis
participant "MWPP://v1/provide-historical-pm-data-of-device" as MWPP
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-capability" as AirInterfaceCapa

LinkVis -> MWPP: [{MountName, timeStamp}] (apiKeyAuth)
activate MWPP

MWPP -> AirInterfaceCapa: {with uuids und localIds of AirInterfaces from RequestForProvidingHistoricalPmDataCausesIdentifyingAirandEthernetInterfaces} (apiKeyAuth)
AirInterfaceCapa --> MWPP: {entire AirInterfaceCapabilities from cache}

deactivate MWPP

@enduml