@startuml 006_ReadingHistoricalEthernetContainerPerformanceFromCache
skinparam responseMessageBelowArrow true

title
RequestForProvidingHistoricalPmDataCausesReadingHistoricalEthernetContainerPerformanceFromCache
end title

participant "LinkVis" as LinkVis
participant "MWPP://v1/provide-historical-pm-data-of-device" as MWPP
participant "<i>RequestForProvidingHistoricalPmDataCausesReadingLtpStructure</i>" as LTPs
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/\nlayer-protocol={localId}/ethernet-container-2-0:ethernet-container-pac/ethernet-container-historical-performances" as EthernetPm

LinkVis -> MWPP: {MountName, timeStamp}<sub>i</sub> (apiKeyAuth)
activate MWPP
LTPs --> MWPP: [{uuid, localId, layerProtocolName}]
loop for each Ltp where LayerProtocolName==ETHERNET_CONTAINER_LAYER obtained from RequestForProvidingHistoricalPmDataCausesReadingLtpStructure
    MWPP -> EthernetPm: {MountName,uuid, localId} (apiKeyAuth)
    EthernetPm --> MWPP: {entire EthernetContainerPerformances from cache}

    note over MWPP
    Keep only entries of performance measurements 
    WHERE
    granularity-period == TYPE_PERIOD-15-MIN
    AND
    period-end-time > timeStamp
    Discard the rest
    end note
end
deactivate MWPP

@enduml