@startuml GlobalMwPerformanceProxy
skinparam responseMessageBelowArrow true

title
GlobalMwPerformanceProxy
end title

participant "LinkVis" as LinkVis
participant "MWPP://v1/provide-historical-pm-data-of-device" as MWPP
participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>ReadingNameOfAirAndEthernetInterfaces</i>" as Names
participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>IdentifyingPhysicalLinkAggregations</i>" as PhysicalAggregations
participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>ReadingAirInterfaceConfigurationFromCache</i>" as AirInterfaceConfig
participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>ReadingAirInterfaceCapabilitiesFromCache</i>" as AirInterfaceCapa
participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>ReadingHistoricalAirInterfacePerformanceFromCache</i>" as AirInterfacePm
participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>ReadingHistoricalEthernetContainerPerformanceFromCache</i>" as EthernetPm

LinkVis -> MWPP: [{MountName, timeStamp}<sub>i</sub>] (apiKeyAuth)
activate MWPP
loop for each i-th pair {MountName, timeStamp}
    Names --> MWPP: [{externalLabel/originalLtpName}]
    PhysicalAggregations--> MWPP: [{externalLabel/originalLtpName}]
    AirInterfaceConfig --> MWPP: [{atpc-is-on, transmission-mode-min, transmission-mode-max}]
    AirInterfaceCapa --> MWPP: [{entire AirInterfaceCapabilities from cache}]
    AirInterfacePm --> MWPP: [{entire AirInterfaceHistoricalPerformance from cache}]
    EthernetPm --> MWPP: [{entire EthernetContainerPerformances from cache}]
end
MWPP --> LinkVis: ResponseBody: [{Link-id, AirInterfaceConfigs, AirInterfaceCapabilities,\n AirInterfaceHistoricalPerformance, EthernetInterfaceName,\n EthernetHistoricalPerformance}] of Ltps in given mounts 
deactivate MWPP

@enduml